name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    # This allows running it on any branch manually:
    # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # All paths should be lowercase or we might have issues
      # when switching between case-sensitive and case-insensitive systems such as Linux and Windows.
      - run: '! ( find . -not -name README.md -not -path "./.git/*" | grep [A-Z] && echo "Asset names/paths must be all lowercase" )'
